[package]
name = "rust_decompress_search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rust_decompress_search"
path = "src/lib.rs"

[dependencies]
zip = "0.6.2"
regex = "1"
anyhow = "1.0"